#!/usr/bin/env node
// scripts/list-scenarios.ts
// ─────────────────────────────────────────────────────────────────────────────
// Prints a human-readable summary of EVERY BDD scenario in the test suite.
// Also writes the output to SCENARIOS.md so it stays up-to-date.
//
// Usage:
//   npm run scenarios          → prints to terminal + updates SCENARIOS.md
//   npx ts-node scripts/list-scenarios.ts
// ─────────────────────────────────────────────────────────────────────────────

import fs   from 'fs';
import path from 'path';

// ── Import all scenarios directly (ts-node resolves TypeScript) ───────────────
import { SCENARIO_REGISTRY } from '../tests/scenarios/index';

// ── Helpers ───────────────────────────────────────────────────────────────────
const TAG_COLORS: Record<string, string> = {
  '@smoke':      '\x1b[32m', // green
  '@regression': '\x1b[33m', // yellow
  default:       '\x1b[36m', // cyan
};
const RESET = '\x1b[0m';
const BOLD  = '\x1b[1m';
const DIM   = '\x1b[2m';

function colorTag(tag: string): string {
  const color = TAG_COLORS[tag] ?? TAG_COLORS.default;
  return `${color}${tag}${RESET}`;
}

function tagBadge(tag: string): string {
  // Markdown badge-style for .md output
  const color = tag === '@smoke' ? 'brightgreen' : tag === '@regression' ? 'yellow' : 'blue';
  const label = tag.replace('@', '');
  return `![${label}](https://img.shields.io/badge/${label}-${color}?style=flat-square)`;
}

// ── Build terminal output ─────────────────────────────────────────────────────
let terminalOutput = '';
let markdownOutput = '';

const totalScenarios = Object.values(SCENARIO_REGISTRY).reduce((n, arr) => n + arr.length, 0);
const totalFeatures  = Object.keys(SCENARIO_REGISTRY).length;

// Terminal header
terminalOutput += `\n${BOLD}╔══════════════════════════════════════════════════════════════╗${RESET}\n`;
terminalOutput += `${BOLD}║         WowStore E2E — BDD Scenario Coverage Report          ║${RESET}\n`;
terminalOutput += `${BOLD}╚══════════════════════════════════════════════════════════════╝${RESET}\n`;
terminalOutput += `\n${DIM}Features: ${totalFeatures}   Scenarios: ${totalScenarios}${RESET}\n`;

// Markdown header
markdownOutput += `# WowStore E2E — BDD Scenario Coverage\n\n`;
markdownOutput += `> Auto-generated by \`npm run scenarios\`. Do not edit manually.\n\n`;
markdownOutput += `**Features:** ${totalFeatures} &nbsp; | &nbsp; **Scenarios:** ${totalScenarios}\n\n`;
markdownOutput += `---\n\n`;

// ── Per-feature output ────────────────────────────────────────────────────────
for (const [feature, scenarios] of Object.entries(SCENARIO_REGISTRY)) {
  terminalOutput += `\n${BOLD}▶ Feature: ${feature}${RESET}  ${DIM}(${scenarios.length} scenario${scenarios.length !== 1 ? 's' : ''})${RESET}\n`;
  terminalOutput += `${DIM}${'─'.repeat(60)}${RESET}\n`;

  markdownOutput += `## 📋 ${feature}\n\n`;
  markdownOutput += `| # | Scenario | Tags |\n`;
  markdownOutput += `|---|----------|------|\n`;

  scenarios.forEach((s, i) => {
    const tagStr    = s.tags.map(colorTag).join(' ');
    const tagMd     = s.tags.map(tagBadge).join(' ');
    const idLabel   = `${DIM}[${s.id}]${RESET}`;
    const num       = String(i + 1).padStart(2, ' ');

    // Extract just the scenario title line from gherkin
    const scenarioLine = s.gherkin
      .split('\n')
      .find(l => l.trim().startsWith('Scenario:'))
      ?.replace('Scenario:', '')
      .trim() ?? s.title;

    terminalOutput += `  ${DIM}${num}.${RESET} ${scenarioLine}\n`;
    terminalOutput += `      ${idLabel} ${tagStr || `${DIM}(no tags)${RESET}`}\n`;

    markdownOutput += `| ${i + 1} | **${scenarioLine}** \`${s.id}\` | ${tagMd || '—'} |\n`;
  });

  markdownOutput += `\n`;
}

// ── Summary by tag ────────────────────────────────────────────────────────────
const allScenarios = Object.values(SCENARIO_REGISTRY).flat();
const tagCounts: Record<string, number> = {};
for (const s of allScenarios) {
  for (const tag of s.tags) {
    tagCounts[tag] = (tagCounts[tag] ?? 0) + 1;
  }
}

if (Object.keys(tagCounts).length > 0) {
  terminalOutput += `\n${BOLD}Tag Summary:${RESET}\n`;
  for (const [tag, count] of Object.entries(tagCounts)) {
    terminalOutput += `  ${colorTag(tag)}  ${count} scenario${count !== 1 ? 's' : ''}\n`;
  }

  markdownOutput += `---\n\n## 🏷️ Tag Summary\n\n`;
  markdownOutput += `| Tag | Count |\n|-----|-------|\n`;
  for (const [tag, count] of Object.entries(tagCounts)) {
    markdownOutput += `| \`${tag}\` | ${count} |\n`;
  }
  markdownOutput += `\n`;
}

markdownOutput += `---\n\n*Generated at: ${new Date().toISOString()}*\n`;

// ── Print to terminal ─────────────────────────────────────────────────────────
terminalOutput += `\n${DIM}SCENARIOS.md updated ✅${RESET}\n\n`;
console.log(terminalOutput);

// ── Write SCENARIOS.md ────────────────────────────────────────────────────────
const outputPath = path.join(process.cwd(), 'SCENARIOS.md');
fs.writeFileSync(outputPath, markdownOutput, 'utf-8');
